openapi: 3.0.3
info:
  title: kazyon-loyalty
  description: |-
    This project consist of two apis to create new user in kazyon-loyalty
    <br> <h2>  API (create New Customer) </h2> will be called to create new user using mobile number and otp send to user.
    <br> <h2>  API (validateOtp) </h2> will be called validate mobileNumber and otp.
    
  

  contact:
    email: mohamed.nasr@kazyon.com
  version: 1.0.01

paths:
  /createNewCustomer:
    post:
      tags:
        - service
      summary: create new user in kazyon-loyalty using customer mobileNumber
      description: This service will be called to create new user
      operationId: getServicesInfo
      parameters:
          - $ref: '#/components/parameters/authorizationHeaderUsername'
          - $ref: '#/components/parameters/authorizationHeaderPassword'
      requestBody:
                content:
                  application/json:
                    schema:
                        $ref: '#/components/schemas/newCustomerRequest'
      

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/newCustomerResponse'      

        '401':
          $ref: '#/components/responses/UnauthorizedError'
          
  /validateOtp:
      post:
        tags:
          - service
        summary: validate Otp for customer using mobileNumber and otp
        description: This service will validate Otp
        operationId: validateOtp
        parameters:
          - $ref: '#/components/parameters/authorizationHeaderUsername'
          - $ref: '#/components/parameters/authorizationHeaderPassword'
        requestBody:
                content:
                  application/json:
                    schema:
                        $ref: '#/components/schemas/validateOtpRequest'
        
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                    $ref: '#/components/schemas/validateOTPResponse'      
  
          '401':
            $ref: '#/components/responses/UnauthorizedError'
            
 
 

components:  
  parameters:
    authorizationHeaderUsername:
      name: Username
      in: header 
      required: true
      schema:
        type: string
        example: 1

    authorizationHeaderPassword:
      name: Password
      in: header 
      required: true
      schema:
        type: string
        example: dXNlcm5hbWU6cGFz 
        
        
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid

  schemas:
     validateOtpRequest:
        type: object
        properties:
          mobileNumber:
            type: string
            description: mobileNumber should be valid 
            example: "01100112233"
          otp:
            type: string
            example: 246888 
     validateOTPResponse:
        type: object
        properties:
          statusCode:
            description:  statusCode=201 means new user was created || statusCode=400  otp or mobile number not valid
            type: string
            example: "201 || 400"
          statusMessage:
            type: string
            example: "otp is correct and new user was created || otp or mobile number not valid"
          
     newCustomerRequest:
        type: object
        properties:
          mobileNumber:
            type: string
            description: mobileNumber should be valid 
            example: "01100112233"
          storeId: 
            type: string
            description: storeId
            example: 1533
          
     
     newCustomerResponse:
      type: object
      properties:
        statusCode:
          description:  statusCode=409 means user already exist, statusCode=201 Customer created and OTP Sent || statusCode=400 invalid moblie number || statusCode=200 otp sent to user 
          type: string
          example: "409 || 201 || 400 || 200"
        statusMessage:
          type: string
          example: "user Already exist || Customer created and OTP Sent || invalid moblie number || otp sent to user"
        

    