openapi: 3.0.3
info:
  title: kazyon-loyalty
  description: |-
    This project consist of one api to create new user in kazyon-loyalty
    <br> <h2>  API (create New Customer) </h2> will be called to create new user using mobile number.
  

  contact:
    email: mohamed.nasr@kazyon.com
  version: 1.0.01

paths:
  /createNewCustomer:
    post:
      tags:
        - service
      summary: create new user in kazyon-loyalty using customer mobileNumber
      description: This service will be called to create new user
      operationId: getServicesInfo
      parameters:
        - $ref: '#/components/parameters/storeCode'
      requestBody:
                content:
                application/json:
                  schema:
                      $ref: '#/components/schemas/newCustomerRequest'
      

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/newCustomerResponse'      

        '401':
          $ref: '#/components/responses/UnauthorizedError'
          
  /validateOtp:
      post:
        tags:
          - service
        summary: validate Otp for customer using mobileNumber and otp
        description: This service will validate Otp
        operationId: validateOtp
        parameters:
          - $ref: '#/components/parameters/storeCode'
        requestBody:
                content:
                  application/json:
                    schema:
                        $ref: '#/components/schemas/validateOtpRequest'
        
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                    $ref: '#/components/schemas/validateOTPResponse'      
  
          '401':
            $ref: '#/components/responses/UnauthorizedError'



components:
  parameters:
    storeCode:
      name: token
      in: header
      description: Bearer 
      required: true
      schema:
        type: string
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid

  schemas:
     validateOtpRequest:
        type: object
        properties:
          mobileNumber:
            type: string
            description: mobileNumber should be valid 
            example: "01100112233"
          otp:
            type: string
            example: 246888 
     validateOTPResponse:
        type: object
        properties:
          statusCode:
            description:  statusCode=409 means mobile number not valid, statusCode=201 means new user was created || statusCode=400 invalid otp 
            type: string
            example: "409 || 201 || 400"
          statusMessage:
            type: string
            example: "invalid mobile number || otp is correct and new user was created || invalid otp"
          
     newCustomerRequest:
        type: object
        properties:
          mobileNumber:
            type: string
            description: mobileNumber should be valid 
            example: "01100112233"
          
     
     newCustomerResponse:
      type: object
      properties:
        statusCode:
          description:  statusCode=409 means user already exist and otp is null , statusCode=201 means new user was created and otp is number can be used || statusCode=400 invalid moblie number 
          type: string
          example: "409 || 201 || 400"
        statusMessage:
          type: string
          example: "user Already exist || otp sent to user || invalid moblie number"
        

    